---
name: doctory
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  calendar_date_picker2: ^1.1.5
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  get_it: ^7.7.0
  fluttertoast: ^8.2.8
  flutter_secure_storage: ^9.0.0
  intl_phone_number_input: ^0.7.0
  skeletonizer: ^1.4.2
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.3










  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.4.0



dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/doctory.png
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: Cairo
    fonts:
    - asset: assets/fonts/Cairo-Black.ttf
      weight: 900
    - asset: assets/fonts/Cairo-Bold.ttf
      weight: 700
    - asset: assets/fonts/Cairo-ExtraBold.ttf
      weight: 800
    - asset: assets/fonts/Cairo-ExtraLight.ttf
      weight: 200
    - asset: assets/fonts/Cairo-Medium.ttf
      weight: 500
    - asset: assets/fonts/Cairo-Regular.ttf
      weight: 400
    - asset: assets/fonts/Cairo-SemiBold.ttf
      weight: 600
flutter_intl:
  enabled: true
